# Generated by Django 5.2.9 on 2025-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAnimal', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('arrival_date', models.DateField()),
            ],
        ),
    ]
